server:
  port: 80
#  rabbitmq配置
spring:
  rabbitmq:
    host: 47.100.236.197
    port: 5672
    username: admin
    password: zysadmin
    virtual-host: my_vhost
  redis:
    host: insozhao.cn
    port: 9736
    password: TGQzys123
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 0
    timeout: 1000

#  数据库连接池配置
