server:
  port: 80
  servlet:
    context-path: /online-work

spring:
  #  rabbitmq配置
  rabbitmq:
    host: 47.100.236.197
    port: 5672
    username: admin
    password: zysadmin
    virtual-host: my_vhost
#    redis配置
  redis:
    host: insozhao.cn
    port: 9736
    password: TGQzys123
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 0
    timeout: 1000
#    hikari连接池配置
  datasource:
    url: jdbc:mysql://insozhao.cn:3306/wangxiuxiu
    password: zysabc123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
#    数据源其它配置
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HiKari_CP
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: select 1
#      mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.insozhao.beans
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#   云通讯
yuntongxun:
  accountSid: 8aaf07086c8a1560016cb2d1b10d1bd3
  accountToken: 591e0c582b924a8896252ee1c9c6464b
  AppId: 8aaf07086c8a1560016cb2d1b15f1bd9
#  验证码过期时间
  expireTime: 3
